### ISSUE TITLE
Webscrape SFSU website 

### ISSUE THREAD

**Issue by Krispyru** [AlexHappyCode/CSC-SFSU_BOT#3]
We need to do this to get easily accessible class information for people inside the discord server

**Comment by SaberSams** [comment]
I created a web scraping script in the dev branch. I still need to integrate it into the bot but I believe it works.

**Comment by SaberSams** [comment]
A quick search now returns a basic list for the current semester. A new issue should be opened if we decide to add more functionality

**Comment by SaberSams** [comment]
Bot now scrapes again in the new pull request
